####  Exploring [Numpy](https://numpy.org/)
- Numpy stands for Numerical python and is the core library for numeric and scientific computing
- Some of the examples explored here
    - Single and multi dimensional array example and checking and changing the shape of numpy matrix
    - Different ways of initializing numpy array
    - Different numpy join methods (vstack, hstack, column_stack)
    - Numpy intersection and difference
    - Different mathematical operations on Numpy array
    - Different ways of creating Numpy matrix and some operations (extracting rows and columns, transpose)
    - Saving and loading Numpy array / matrix

In [1]:
%load_ext watermark
%load_ext lab_black

In [2]:
import numpy as np
from rich import print, pretty

pretty.install()

%watermark -a "Sudarshan Koirala" -iv -v

Author: Sudarshan Koirala

Python implementation: CPython
Python version       : 3.8.5
IPython version      : 7.23.1

rich : 10.2.0
numpy: 1.20.3



#### Single and Multi Dimensional Array

In [3]:
# single dimensional array
np_single_dimensional_array = np.array([2, 3, 4, 5])  # passing list
np_single_dimensional_array

array([2, 3, 4, 5])

In [4]:
# multi dimensional array
np_multi_dimensional_array = np.array(
    [[2, 3, 4, 5], [20, 30, 40, 50]]
)  # passing list of list
np_multi_dimensional_array

array([[ 2,  3,  4,  5],
       [20, 30, 40, 50]])

In [5]:
# check the type of numpy array -> ndarray stands for n dimensional array
print(type(np_single_dimensional_array))
print(type(np_multi_dimensional_array))

<class 'numpy.ndarray'>

<class 'numpy.ndarray'>

#### Initializing Numpy array with zeros (using method zeros)

In [6]:
numpy_with_zeros = np.zeros((1, 2))
numpy_with_zeros

array([[0., 0.]])

#### Initializing Numpy array with same number (using full method)

In [7]:
numpy_with_same_number = np.full((4, 5), 10)
numpy_with_same_number

array([[10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10]])

#### Initializing Numpy array within a certain range and with random numbers

In [8]:
numpy_within_a_range = np.arange(10, 20)
numpy_within_a_range

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [9]:
numpy_within_a_range_step = np.arange(10, 50, 5)
numpy_within_a_range_step

array([10, 15, 20, 25, 30, 35, 40, 45])

In [10]:
numpy_with_random_number = np.random.randint(1, 100, 5)
numpy_with_random_number

array([28, 42, 75,  8, 30])

#### Checking the shape of numpy arrays and changing dimensions

In [11]:
numpy_with_random_number.shape

(5,)

In [12]:
print(numpy_with_same_number)
print(numpy_with_same_number.shape)

[[10 10 10 10 10]
 [10 10 10 10 10]
 [10 10 10 10 10]
 [10 10 10 10 10]]

(4, 5)

In [13]:
numpy_with_same_number.shape = (5, 4)
print(numpy_with_same_number)
print(numpy_with_same_number.shape)

[[10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]]

(5, 4)

#### Joining Numpy arrays

In [14]:
n1 = np.arange(5, 26, 5)
n2 = np.arange(10, 51, 10)

In [15]:
n1

array([ 5, 10, 15, 20, 25])

In [16]:
n2

array([10, 20, 30, 40, 50])

In [17]:
# vstack (takes tuples)
np.vstack((n1, n2))

array([[ 5, 10, 15, 20, 25],
       [10, 20, 30, 40, 50]])

In [18]:
# hstack(takes tuples too)
np.hstack((n1, n2))

array([ 5, 10, 15, 20, 25, 10, 20, 30, 40, 50])

In [19]:
# column_stack (also takes tuples)
np.column_stack((n1, n2))

array([[ 5, 10],
       [10, 20],
       [15, 30],
       [20, 40],
       [25, 50]])

#### Numpy Intersection and Difference

In [20]:
n1 = np.arange(10, 61, 10)
n2 = np.arange(50, 101, 10)

In [21]:
# intersect1d (common elements in given two arrays)
np.intersect1d(n1, n2)

array([50, 60])

In [22]:
# setdiff1d (elements unique to first numpy array)
np.setdiff1d(n1, n2)

array([10, 20, 30, 40])

In [23]:
# setdiff1d (elements unique to second numpy array)
np.setdiff1d(n2, n1)

array([ 70,  80,  90, 100])

#### Numpy Array Mathematics

In [24]:
n1

array([10, 20, 30, 40, 50, 60])

In [25]:
n2

array([ 50,  60,  70,  80,  90, 100])

In [26]:
# calculates the sum of all the elements from both numpy array
np.sum([n1, n2])

660

In [27]:
# calculates the sum of correspoding column elements
np.sum([n1, n2], axis=0)

array([ 60,  80, 100, 120, 140, 160])

In [28]:
# calculates the sum of correspoinding row elements
np.sum([n1, n2], axis=1)

array([210, 450])

In [29]:
# taking the minimum and maximum values of given numpy array
np.max(n2), np.min(n2)

(100, 50)

In [30]:
# basic addition
n1 = n1 + 2
n1

array([12, 22, 32, 42, 52, 62])

In [31]:
# basic subtraction
n1 = n1 - 1
n1

array([11, 21, 31, 41, 51, 61])

In [32]:
# basic multiplication
n1 = n1 * 2
n1

array([ 22,  42,  62,  82, 102, 122])

In [33]:
# basic division
n1 = n1 / 2
n1

array([11., 21., 31., 41., 51., 61.])

In [34]:
# calculate the mean
np.mean(n1)

36.0

In [35]:
# calculate the standard deviation
np.std(n1)

17.07825127659933

In [36]:
# calculate the median
np.median(n1)

36.0

#### Numpy Matrix

In [38]:
# create numpy matrix example 1
numpy_matrix_example1 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
numpy_matrix_example1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [39]:
# second example of creating numpy matrix
numpy_matrix_example2 = np.arange(0, 6) + np.zeros((3, 1))
numpy_matrix_example2

array([[0., 1., 2., 3., 4., 5.],
       [0., 1., 2., 3., 4., 5.],
       [0., 1., 2., 3., 4., 5.]])

In [41]:
# third way of creating numpy matrix
numpy_matrix_example3 = np.arange(1, 10).reshape(3, 3)
numpy_matrix_example3

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

##### Extracting specific columns or rows

In [42]:
numpy_matrix_example3[0]

array([1, 2, 3])

In [43]:
numpy_matrix_example3[:, 1]

array([2, 5, 8])

In [45]:
numpy_matrix_example3[2, :]

array([7, 8, 9])

##### Numpy Matrix transpose and sum of main diagonal

In [50]:
np.transpose(numpy_matrix_example3)

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [51]:
numpy_matrix_example3.transpose()

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [48]:
# trace of numpy matrix (sum of elements in main diagonal)
numpy_matrix_example3.trace()

15

In [52]:
np.trace(numpy_matrix_example3)

15

##### Numpy matrix multiplication (column of both matrix must be same)

In [53]:
numpy_matrix_example3.dot(numpy_matrix_example2)

array([[  0.,   6.,  12.,  18.,  24.,  30.],
       [  0.,  15.,  30.,  45.,  60.,  75.],
       [  0.,  24.,  48.,  72.,  96., 120.]])

In [55]:
a = np.arange(1, 11).reshape(2, 5)
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [56]:
b = np.arange(1, 10).reshape(3, 3)
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [57]:
print(a.shape)
print(b.shape)

(2, 5)

(3, 3)

In [58]:
# as the column of two matrix is not same, we can't do matrix multiplication.
a.dot(b)

ValueError: shapes (2,5) and (3,3) not aligned: 5 (dim 1) != 3 (dim 0)

#### Saving and loading Numpy array / matrix

In [60]:
# saving the numpy matrix
# when saved .npy is added after the name
np.save("my_numpy", numpy_matrix_example3)

In [61]:
# loading the saved numpy matrix
np.load("my_numpy.npy")

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])